//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroAcademico.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Database : DbContext
    {
        public Database()
            : base("name=Database")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alumno> Alumno { get; set; }
        public virtual DbSet<Asignacion> Asignacion { get; set; }
        public virtual DbSet<Asignatura> Asignatura { get; set; }
        public virtual DbSet<Detalle_Grupos_Asignado> Detalle_Grupos_Asignado { get; set; }
        public virtual DbSet<Detalles_Pensul> Detalles_Pensul { get; set; }
        public virtual DbSet<Docente> Docente { get; set; }
        public virtual DbSet<Grupos> Grupos { get; set; }
        public virtual DbSet<Grupos_Alumno> Grupos_Alumno { get; set; }
        public virtual DbSet<Grupos_Asignado> Grupos_Asignado { get; set; }
        public virtual DbSet<Grupos_Docente> Grupos_Docente { get; set; }
        public virtual DbSet<Grupos_Material> Grupos_Material { get; set; }
        public virtual DbSet<Nota> Nota { get; set; }
        public virtual DbSet<Pensul> Pensul { get; set; }
    }
}
