//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroAcademico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumno
    {
        public int N_Carnet { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string pass { get; set; }
        public Nullable<bool> Estado { get; set; }
        public int id_Alumno { get; set; }
    }
}
