//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroAcademico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asignacion
    {
        public int id_Asignacion { get; set; }
        public int N_Carnet { get; set; }
        public string id_Grupo { get; set; }
    }
}
