//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroAcademico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grupos_Asignado
    {
        public int id_Grupo_Asignado { get; set; }
        public int id_Grupos { get; set; }
        public string id_Asignatura { get; set; }
        public string id_Docente { get; set; }
    }
}
