//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroAcademico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nota
    {
        public int idNOta { get; set; }
        public string idAsignatura { get; set; }
        public Nullable<int> N_Carnet { get; set; }
        public Nullable<int> Acumulado { get; set; }
        public Nullable<int> Examen { get; set; }
        public Nullable<int> Nota_final { get; set; }
        public Nullable<int> Rescate { get; set; }
    }
}
