//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroAcademico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pensul
    {
        public int idPensul { get; set; }
        public int año { get; set; }
        public string descripcion { get; set; }
    }
}
